In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Age_Edu_Ethnicity_HHSpending.xlsx')

In [4]:
df.dropna()

,zip,State,City,"Estimated percent of all people age 25-34, between 2014-2018.","Estimated percent of all people age 35-44, between 2014-2018.","Estimated percent of all people age 45-54, between 2014-2018.","Estimated percent of all people age 55-64, between 2014-2018.","Estimated percent of all people 65 or older, between 2014-2018.",Estimated typical (median) age of all people between 2013-2017.,"Estimated percent of people with a Bachelor's degree, between 20",...,"Estimated average size of a household, between 2014-2018.","Estimated median gross rent, between 2014-2018.","Estimated median value of an owner-occupied home, between 2014-2018","Estimated median income of a household, between 2014-2018.","Estimated median renter cost burden, between 2014-2018.","Estimated median owner cost burden, between 2014-2018.",Estimated percent of all people who were Asian between 2013-2017,Estimated percent of all people who were Black between 2013-2017,Estimated percent of all people who were Hispanic between 2013-2,Estimated percent of all people who were White between 2013-2017
0,00501,NY,HOLTSVILLE,14.950000,11.620000,22.520000,13.010000,10.540000,38.000000,16.000000,...,2.470000,1378.000000,319300.000000,94898.000000,21.500000,23.500000,1.760000,1.760000,21.320000,94.150000
1,00601,PR,ADJUNTAS,13.986667,10.570000,10.866667,10.590000,19.083333,36.666667,16.390000,...,2.673333,514.666667,108700.000000,12740.000000,31.866667,15.333333,1.343333,1.333333,98.146667,79.600000
2,00602,PR,AGUADA,11.242500,12.730000,13.905000,14.912500,18.190000,42.250000,18.270000,...,2.752500,482.000000,110975.000000,18458.500000,29.875000,14.925000,0.250000,4.377500,92.880000,69.382500
3,00603,PR,AGUADILLA,12.026471,12.126471,12.684118,13.198824,20.614118,41.470588,17.274118,...,2.478824,418.562500,109411.764706,15943.823529,32.605882,13.123529,1.193571,4.066429,97.152143,73.247143
4,00604,PR,AGUADILLA,8.730000,17.290000,14.590000,12.110000,12.750000,38.000000,39.250000,...,2.250000,751.000000,154000.000000,26890.000000,26.800000,19.900000,1.000000,5.280000,86.370000,71.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39065,99362,WA,WALLA WALLA,13.748333,11.414167,11.934167,12.212500,16.005833,36.250000,16.554167,...,2.435000,913.727273,202200.000000,53764.454545,32.063636,17.236364,1.625833,2.192500,22.923333,82.373333
39067,99371,WA,WASHTUCNA,13.255000,10.260000,14.145000,14.120000,15.255000,38.500000,12.300000,...,3.130000,758.000000,130000.000000,59630.500000,18.700000,16.150000,0.650000,1.545000,17.265000,86.960000
39068,99401,WA,ANATONE,9.020000,10.380000,12.830000,17.920000,24.830000,49.000000,12.440000,...,3.220000,769.000000,235000.000000,67386.000000,22.400000,16.800000,2.900000,0.220000,2.240000,92.520000
39069,99402,WA,ASOTIN,7.100000,10.180000,12.230000,18.110000,28.680000,51.500000,16.080000,...,3.385000,915.500000,232700.000000,59840.500000,23.500000,16.450000,1.450000,0.955000,3.100000,91.165000
39070,99403,WA,CLARKSTON,11.437500,10.882500,12.391250,15.736250,21.306250,44.250000,15.637500,...,2.748750,749.000000,178762.500000,51569.125000,26.512500,16.987500,0.923750,0.286250,3.276250,94.148750

In [5]:
df_edu = pd.read_excel('Education.xlsx')
df_edu

,zip,"Estimated percent of people with a Bachelor's degree, between 20",Estimated percent of people with a high school diploma and no co,Estimated percent of people with less than a high school diploma,Estimated percent of people with a post graduate degree between,Estimated percent of people with some college or an Associate's
0,501,16.000000,37.650000,7.800000,8.810000,34.590000
1,601,16.390000,22.976667,26.706667,8.616667,25.223333
2,602,18.270000,24.102500,28.165000,8.700000,21.012500
3,603,17.274118,27.545882,28.654706,6.383529,19.615882
4,604,39.250000,14.800000,11.090000,16.940000,19.230000
...,...,...,...,...,...,...
39221,99925,12.340000,38.130000,10.670000,8.000000,30.960000
39222,99926,6.580000,35.760000,8.160000,3.690000,44.900000
39223,99927,12.800000,38.660000,10.450000,5.410000,34.360000
39224,99928,16.510000,27.430000,4.950000,10.270000,41.380000
39225,99929,14.030000,36.620000,11.040000,6.570000,32.900000

In [6]:
df_eth = pd.read_excel('Ethnicity.xlsx')
df_eth

,zip,Estimated percent of all people who were Asian between 2013-2017,Estimated percent of all people who were Black between 2013-2017,Estimated percent of all people who were Hispanic between 2013-2,Estimated percent of all people who were White between 2013-2017
0,501,1.760000,1.760000,21.320000,94.150000
1,601,1.343333,1.333333,98.146667,79.600000
2,602,0.250000,4.377500,92.880000,69.382500
3,603,1.009412,3.694706,97.208235,73.702353
4,604,1.000000,5.280000,86.370000,71.950000
...,...,...,...,...,...
39226,99925,1.290000,0.230000,2.260000,60.870000
39227,99926,1.430000,0.000000,7.660000,13.540000
39228,99927,0.760000,0.180000,2.290000,56.420000
39229,99928,2.240000,0.550000,3.070000,84.660000
39230,99929,3.110000,0.160000,3.150000,65.940000

In [8]:
df_age = pd.read_csv('Age_Output.csv')
df_age

,zip,"Estimated percent of all people age 25-34, between 2014-2018.","Estimated percent of all people age 35-44, between 2014-2018.","Estimated percent of all people age 45-54, between 2014-2018.","Estimated percent of all people age 55-64, between 2014-2018.","Estimated percent of all people 65 or older, between 2014-2018.",Estimated typical (median) age of all people between 2013-2017.
0,501,14.950000,11.620000,22.520000,13.010000,10.540000,38.000000
1,601,13.986667,10.570000,10.866667,10.590000,19.083333,36.666667
2,602,11.242500,12.730000,13.905000,14.912500,18.190000,42.250000
3,603,12.026471,12.126471,12.684118,13.198824,20.614118,41.470588
4,604,8.730000,17.290000,14.590000,12.110000,12.750000,38.000000
...,...,...,...,...,...,...,...
39221,99925,11.460000,11.300000,15.790000,17.440000,12.910000,43.000000
39222,99926,13.700000,9.660000,13.210000,12.970000,12.780000,33.000000
39223,99927,11.870000,11.950000,14.580000,17.640000,17.860000,44.000000
39224,99928,9.720000,12.920000,16.100000,16.460000,15.760000,44.000000
39225,99929,10.590000,8.370000,13.890000,20.570000,22.060000,49.000000

In [9]:
df_hhs = pd.read_excel('HHSpending.xlsx')
df_hhs

,zip,"Estimated average size of a household, between 2014-2018.","Estimated median gross rent, between 2014-2018.","Estimated median value of an owner-occupied home, between 2014-2018","Estimated median income of a household, between 2014-2018.","Estimated median owner cost burden, between 2014-2018.","Estimated median renter cost burden, between 2014-2018."
0,501,2.470000,1378.000000,319300.0,94898.0,23.500000,21.500000
1,601,2.673333,514.666667,108700.0,12740.0,15.333333,31.866667
2,602,2.752500,482.000000,110975.0,18458.5,14.925000,29.875000
3,603,2.481875,418.562500,108950.0,15634.5,13.093750,32.843750
4,604,2.250000,751.000000,154000.0,26890.0,19.900000,26.800000
...,...,...,...,...,...,...,...
38441,99925,2.690000,878.000000,223900.0,63462.0,13.700000,22.100000
38442,99926,3.460000,671.000000,143100.0,53409.0,11.600000,18.200000
38443,99927,2.430000,860.000000,165100.0,46411.0,11.800000,22.600000
38444,99928,2.620000,1435.000000,309600.0,85362.0,17.200000,27.200000
38445,99929,2.240000,809.000000,212600.0,57583.0,16.700000,28.100000

In [10]:
def merger(*args):
    new = args[0]
    for i in range(len(args)-1):
        new = pd.merge(new,args[i+1],how = 'inner')
    return new
df_total = merger(df_age,df_edu,df_eth,df_hhs)
df_total

,zip,"Estimated percent of all people age 25-34, between 2014-2018.","Estimated percent of all people age 35-44, between 2014-2018.","Estimated percent of all people age 45-54, between 2014-2018.","Estimated percent of all people age 55-64, between 2014-2018.","Estimated percent of all people 65 or older, between 2014-2018.",Estimated typical (median) age of all people between 2013-2017.,"Estimated percent of people with a Bachelor's degree, between 20",Estimated percent of people with a high school diploma and no co,Estimated percent of people with less than a high school diploma,...,Estimated percent of all people who were Asian between 2013-2017,Estimated percent of all people who were Black between 2013-2017,Estimated percent of all people who were Hispanic between 2013-2,Estimated percent of all people who were White between 2013-2017,"Estimated average size of a household, between 2014-2018.","Estimated median gross rent, between 2014-2018.","Estimated median value of an owner-occupied home, between 2014-2018","Estimated median income of a household, between 2014-2018.","Estimated median owner cost burden, between 2014-2018.","Estimated median renter cost burden, between 2014-2018."
0,501,14.950000,11.620000,22.520000,13.010000,10.540000,38.000000,16.000000,37.650000,7.800000,...,1.760000,1.760000,21.320000,94.150000,2.470000,1378.000000,319300.0,94898.0,23.500000,21.500000
1,601,13.986667,10.570000,10.866667,10.590000,19.083333,36.666667,16.390000,22.976667,26.706667,...,1.343333,1.333333,98.146667,79.600000,2.673333,514.666667,108700.0,12740.0,15.333333,31.866667
2,602,11.242500,12.730000,13.905000,14.912500,18.190000,42.250000,18.270000,24.102500,28.165000,...,0.250000,4.377500,92.880000,69.382500,2.752500,482.000000,110975.0,18458.5,14.925000,29.875000
3,603,12.026471,12.126471,12.684118,13.198824,20.614118,41.470588,17.274118,27.545882,28.654706,...,1.009412,3.694706,97.208235,73.702353,2.481875,418.562500,108950.0,15634.5,13.093750,32.843750
4,604,8.730000,17.290000,14.590000,12.110000,12.750000,38.000000,39.250000,14.800000,11.090000,...,1.000000,5.280000,86.370000,71.950000,2.250000,751.000000,154000.0,26890.0,19.900000,26.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38441,99925,11.460000,11.300000,15.790000,17.440000,12.910000,43.000000,12.340000,38.130000,10.670000,...,1.290000,0.230000,2.260000,60.870000,2.690000,878.000000,223900.0,63462.0,13.700000,22.100000
38442,99926,13.700000,9.660000,13.210000,12.970000,12.780000,33.000000,6.580000,35.760000,8.160000,...,1.430000,0.000000,7.660000,13.540000,3.460000,671.000000,143100.0,53409.0,11.600000,18.200000
38443,99927,11.870000,11.950000,14.580000,17.640000,17.860000,44.000000,12.800000,38.660000,10.450000,...,0.760000,0.180000,2.290000,56.420000,2.430000,860.000000,165100.0,46411.0,11.800000,22.600000
38444,99928,9.720000,12.920000,16.100000,16.460000,15.760000,44.000000,16.510000,27.430000,4.950000,...,2.240000,0.550000,3.070000,84.660000,2.620000,1435.000000,309600.0,85362.0,17.200000,27.200000
38445,99929,10.590000,8.370000,13.890000,20.570000,22.060000,49.000000,14.030000,36.620000,11.040000,...,3.110000,0.160000,3.150000,65.940000,2.240000,809.000000,212600.0,57583.0,16.700000,28.100000

In [16]:
df_total = df_total.drop_duplicates().set_index('zip')

In [17]:
df_total

,"Estimated percent of all people age 25-34, between 2014-2018.","Estimated percent of all people age 35-44, between 2014-2018.","Estimated percent of all people age 45-54, between 2014-2018.","Estimated percent of all people age 55-64, between 2014-2018.","Estimated percent of all people 65 or older, between 2014-2018.",Estimated typical (median) age of all people between 2013-2017.,"Estimated percent of people with a Bachelor's degree, between 20",Estimated percent of people with a high school diploma and no co,Estimated percent of people with less than a high school diploma,Estimated percent of people with a post graduate degree between,...,Estimated percent of all people who were Asian between 2013-2017,Estimated percent of all people who were Black between 2013-2017,Estimated percent of all people who were Hispanic between 2013-2,Estimated percent of all people who were White between 2013-2017,"Estimated average size of a household, between 2014-2018.","Estimated median gross rent, between 2014-2018.","Estimated median value of an owner-occupied home, between 2014-2018","Estimated median income of a household, between 2014-2018.","Estimated median owner cost burden, between 2014-2018.","Estimated median renter cost burden, between 2014-2018."
zip,,,,,,,,,,,,,,,,,,,,,
501,14.950000,11.620000,22.520000,13.010000,10.540000,38.000000,16.000000,37.650000,7.800000,8.810000,...,1.760000,1.760000,21.320000,94.150000,2.470000,1378.000000,319300.0,94898.0,23.500000,21.500000
601,13.986667,10.570000,10.866667,10.590000,19.083333,36.666667,16.390000,22.976667,26.706667,8.616667,...,1.343333,1.333333,98.146667,79.600000,2.673333,514.666667,108700.0,12740.0,15.333333,31.866667
602,11.242500,12.730000,13.905000,14.912500,18.190000,42.250000,18.270000,24.102500,28.165000,8.700000,...,0.250000,4.377500,92.880000,69.382500,2.752500,482.000000,110975.0,18458.5,14.925000,29.875000
603,12.026471,12.126471,12.684118,13.198824,20.614118,41.470588,17.274118,27.545882,28.654706,6.383529,...,1.009412,3.694706,97.208235,73.702353,2.481875,418.562500,108950.0,15634.5,13.093750,32.843750
604,8.730000,17.290000,14.590000,12.110000,12.750000,38.000000,39.250000,14.800000,11.090000,16.940000,...,1.000000,5.280000,86.370000,71.950000,2.250000,751.000000,154000.0,26890.0,19.900000,26.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99925,11.460000,11.300000,15.790000,17.440000,12.910000,43.000000,12.340000,38.130000,10.670000,8.000000,...,1.290000,0.230000,2.260000,60.870000,2.690000,878.000000,223900.0,63462.0,13.700000,22.100000
99926,13.700000,9.660000,13.210000,12.970000,12.780000,33.000000,6.580000,35.760000,8.160000,3.690000,...,1.430000,0.000000,7.660000,13.540000,3.460000,671.000000,143100.0,53409.0,11.600000,18.200000
99927,11.870000,11.950000,14.580000,17.640000,17.860000,44.000000,12.800000,38.660000,10.450000,5.410000,...,0.760000,0.180000,2.290000,56.420000,2.430000,860.000000,165100.0,46411.0,11.800000,22.600000
99928,9.720000,12.920000,16.100000,16.460000,15.760000,44.000000,16.510000,27.430000,4.950000,10.270000,...,2.240000,0.550000,3.070000,84.660000,2.620000,1435.000000,309600.0,85362.0,17.200000,27.200000
99929,10.590000,8.370000,13.890000,20.570000,22.060000,49.000000,14.030000,36.620000,11.040000,6.570000,...,3.110000,0.160000,3.150000,65.940000,2.240000,809.000000,212600.0,57583.0,16.700000,28.100000

In [20]:
dict_zip_county = pd.read_excel('uszips.xlsx')

In [21]:
dict_zip_city = pd.read_csv('zip-codes-database-FREE.csv')

In [22]:
dict_zip_city

,ZipCode,City,State,Latitude,Longitude,Classification,Population
0,501,HOLTSVILLE,NY,40.8179,-73.0453,U,0
1,544,HOLTSVILLE,NY,40.7888,-73.0394,U,0
2,601,ADJUNTAS,PR,18.1967,-66.7367,NaN,18570
3,602,AGUADA,PR,18.3529,-67.1775,NaN,41520
4,603,AGUADILLA,PR,18.4586,-67.1299,NaN,54689
...,...,...,...,...,...,...,...
41725,99926,METLAKATLA,AK,55.1450,-131.5439,P,1460
41726,99927,POINT BAKER,AK,56.1513,-133.3490,P,94
41727,99928,WARD COVE,AK,55.4104,-131.7237,P,0
41728,99929,WRANGELL,AK,56.1800,-132.0304,P,2338
41729,99950,KETCHIKAN,AK,55.8159,-132.9799,P,0

In [27]:
dict_zip_city[['ZipCode','City','State']].merge(df_total,left_on = 'ZipCode', right_on = df_total.index, how = 'right')

,ZipCode,City,State,"Estimated percent of all people age 25-34, between 2014-2018.","Estimated percent of all people age 35-44, between 2014-2018.","Estimated percent of all people age 45-54, between 2014-2018.","Estimated percent of all people age 55-64, between 2014-2018.","Estimated percent of all people 65 or older, between 2014-2018.",Estimated typical (median) age of all people between 2013-2017.,"Estimated percent of people with a Bachelor's degree, between 20",...,Estimated percent of all people who were Asian between 2013-2017,Estimated percent of all people who were Black between 2013-2017,Estimated percent of all people who were Hispanic between 2013-2,Estimated percent of all people who were White between 2013-2017,"Estimated average size of a household, between 2014-2018.","Estimated median gross rent, between 2014-2018.","Estimated median value of an owner-occupied home, between 2014-2018","Estimated median income of a household, between 2014-2018.","Estimated median owner cost burden, between 2014-2018.","Estimated median renter cost burden, between 2014-2018."
0,501,HOLTSVILLE,NY,14.950000,11.620000,22.520000,13.010000,10.540000,38.000000,16.000000,...,1.760000,1.760000,21.320000,94.150000,2.470000,1378.000000,319300.0,94898.0,23.500000,21.500000
1,601,ADJUNTAS,PR,13.986667,10.570000,10.866667,10.590000,19.083333,36.666667,16.390000,...,1.343333,1.333333,98.146667,79.600000,2.673333,514.666667,108700.0,12740.0,15.333333,31.866667
2,602,AGUADA,PR,11.242500,12.730000,13.905000,14.912500,18.190000,42.250000,18.270000,...,0.250000,4.377500,92.880000,69.382500,2.752500,482.000000,110975.0,18458.5,14.925000,29.875000
3,603,AGUADILLA,PR,12.026471,12.126471,12.684118,13.198824,20.614118,41.470588,17.274118,...,1.009412,3.694706,97.208235,73.702353,2.481875,418.562500,108950.0,15634.5,13.093750,32.843750
4,604,AGUADILLA,PR,8.730000,17.290000,14.590000,12.110000,12.750000,38.000000,39.250000,...,1.000000,5.280000,86.370000,71.950000,2.250000,751.000000,154000.0,26890.0,19.900000,26.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38469,99926,METLAKATLA,AK,13.700000,9.660000,13.210000,12.970000,12.780000,33.000000,6.580000,...,1.430000,0.000000,7.660000,13.540000,3.460000,671.000000,143100.0,53409.0,11.600000,18.200000
38470,99927,POINT BAKER,AK,11.870000,11.950000,14.580000,17.640000,17.860000,44.000000,12.800000,...,0.760000,0.180000,2.290000,56.420000,2.430000,860.000000,165100.0,46411.0,11.800000,22.600000
38471,99928,WARD COVE,AK,9.720000,12.920000,16.100000,16.460000,15.760000,44.000000,16.510000,...,2.240000,0.550000,3.070000,84.660000,2.620000,1435.000000,309600.0,85362.0,17.200000,27.200000
38472,99929,WRANGELL,AK,10.590000,8.370000,13.890000,20.570000,22.060000,49.000000,14.030000,...,3.110000,0.160000,3.150000,65.940000,2.240000,809.000000,212600.0,57583.0,16.700000,28.100000
38473,54472,NaN,NaN,9.400000,11.460000,13.930000,15.610000,21.800000,45.000000,13.750000,...,2.430000,0.000000,2.610000,95.290000,2.280000,709.000000,135300.0,46875.0,17.500000,31.600000

In [30]:
dict_zip_city[['ZipCode','City','State']].merge(df_total,left_on = 'ZipCode', right_on = df_total.index, how = 'right')\
    .reset_index().set_index('ZipCode').to_csv('AgeEduEthHHS.csv')